### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by renaudcerrato** [hydrabus/hydranfc#1]
What's the usage license of the HydraNFC hardware?

**Comment by bvernoux** [comment]
The License of the HydraNFC hardware is defined here:
* https://github.com/hydrabus/hydranfc/blob/master/hardware/README.md

Extract of the README license part:
* HydraNFC_1_1_Rev1 and HydraNFC_Antenna_1_0_Rev0: Hardware license [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/) (for commercial license contact info@hydrabus.com)
